# Análise Exploratória — banco_sbbrasil_2023-20250326.csv



Passos:
- Carregar dados
- Ver shape, colunas e tipos
- Contagem de valores nulos
- Estatísticas descritivas
- Distribuições e contagens para colunas-chave

In [2]:
# 1) Importar bibliotecas e carregar o arquivo
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

csv_path = r"d:\IC\banco_sbbrasil_2023_XLM_CSV\banco_sbbrasil_2023-20250326.csv"
# Ler com engine='python' e separador padrão ','
df = pd.read_csv(csv_path, sep=',', engine='python', encoding='utf-8')

print('Carregado em:', csv_path)
print('shape =', df.shape)
df.head()

Carregado em: d:\IC\banco_sbbrasil_2023_XLM_CSV\banco_sbbrasil_2023-20250326.csv
shape = (40720, 413)

,codigo,setor,cod_uf,uf2,regiao,cidade,capital,interior,capint,pessoas_dom,...,catdai,edentulismo,urgencia_agrupado,sm,smcat,rendapercapita,estrato,wi_pesodel,grupo_estudo,ano
0,1,110020505000003,11,5,1,PORTO VELHO,1,0,1,5.0,...,NaN,NaN,0.0,2.045455,3,540.0,40,58.3,05_anos,3
1,2,110020505000003,11,5,1,PORTO VELHO,1,0,1,5.0,...,NaN,NaN,2.0,2.878788,3,760.0,40,58.3,05_anos,3
2,3,110020505000003,11,5,1,PORTO VELHO,1,0,1,2.0,...,NaN,NaN,2.0,0.984848,1,650.0,40,47.4,05_anos,3
3,4,110020505000003,11,5,1,PORTO VELHO,1,0,1,5.0,...,NaN,NaN,2.0,NaN,9,NaN,40,58.3,05_anos,3
4,5,110020505000003,11,5,1,PORTO VELHO,1,0,1,7.0,...,NaN,NaN,2.0,NaN,9,NaN,40,47.4,05_anos,3

In [3]:
# 2) Colunas, tipos e nulos
print('Colunas ({}):'.format(len(df.columns)))
print(df.columns.tolist())

print('\nDtypes:')
print(df.dtypes)

print('\nNulos por coluna (count):')
nulls = df.isnull().sum()
print(nulls[nulls>0].sort_values(ascending=False).head(20))

Colunas (413):
['codigo', 'setor', 'cod_uf', 'uf2', 'regiao', 'cidade', 'capital', 'interior', 'capint', 'pessoas_dom', 'dormitorio_dom', 'televisao', 'geladeira', 'aparelhosom', 'microondas', 'telfixo', 'telcelular', 'maqlavarroupa', 'maqlavarlouca', 'computador', 'carros', 'rendafamiliar', 'internet', 'bpc', 'bolsafamilia', 'outrosprogsociais', 'agua', 'idade', 'sexo', 'cor_raca', 'ler_escrever', 'frequenta_escola', 'escol_mae', 'anosestudo_mae', 'escolaridade', 'anosestudo', 'procura_servico', 'tipo_servico_procurado', 'utilizacao_servico', 'tipo_servico_utilizado', 'motivo_consulta', 'aval_servico_utilizado', 'plano_odontologico', 'dor_dente', 'int_dor_dente', 'dor_face', 'int_dor_face', 'autoavaliacao_sb', 'autoavaliacao_nt', 'motivo_nt', 'autoavaliacao_nprot', 'autorrelato_implante', 'SOHO_5_1', 'SOHO_5_2', 'SOHO_5_3', 'SOHO_5_4', 'SOHO_5_5', 'SOHO_5_6', 'SOHO_5_7', 'SOHO_5_pais_1', 'SOHO_5_pais_2', 'SOHO_5_pais_3', 'SOHO_5_pais_4', 'SOHO_5_pais_5', 'SOHO_5_pais_6', 'SOHO_5_pais_7', 'oidp1', 'oidp2', 'oidp3', 'oidp4', 'oidp5', 'oidp6', 'oidp7', 'oidp8', 'oidp9', 'tipo_denticao', 'coroa55', 'pufa55', 'nt55', 'coroa54', 'pufa54', 'nt54', 'coroa53', 'pufa53', 'nt53', 'coroa52', 'pufa52', 'nt52', 'coroa51', 'pufa51', 'nt51', 'coroa61', 'pufa61', 'nt61', 'coroa62', 'pufa62', 'nt62', 'coroa63', 'pufa63', 'nt63', 'coroa64', 'pufa64', 'nt64', 'coroa65', 'pufa65', 'nt65', 'coroa75', 'pufa75', 'nt75', 'coroa74', 'pufa74', 'nt74', 'coroa73', 'pufa73', 'nt73', 'coroa72', 'pufa72', 'nt72', 'coroa71', 'pufa71', 'nt71', 'coroa81', 'pufa81', 'nt81', 'coroa82', 'pufa82', 'nt82', 'coroa83', 'pufa83', 'nt83', 'coroa84', 'pufa84', 'nt84', 'coroa85', 'pufa85', 'nt85', 'dsup', 'coroa18', 'raiz18', 'pufa18', 'nt18', 'coroa17', 'raiz17', 'pufa17', 'nt17', 'coroa16', 'raiz16', 'pufa16', 'nt16', 'coroa15', 'raiz15', 'pufa15', 'nt15', 'coroa14', 'raiz14', 'pufa14', 'nt14', 'coroa13', 'raiz13', 'pufa13', 'nt13', 'coroa12', 'raiz12', 'pufa12', 'nt12', 'coroa11', 'raiz11', 'pufa11', 'nt11', 'coroa21', 'raiz21', 'pufa21', 'nt21', 'coroa22', 'raiz22', 'pufa22', 'nt22', 'coroa23', 'raiz23', 'pufa23', 'nt23', 'coroa24', 'raiz24', 'pufa24', 'nt24', 'coroa25', 'raiz25', 'pufa25', 'nt25', 'coroa26', 'raiz26', 'pufa26', 'nt26', 'coroa27', 'raiz27', 'pufa27', 'nt27', 'coroa28', 'raiz28', 'pufa28', 'nt28', 'dinf', 'coroa38', 'raiz38', 'pufa38', 'nt38', 'coroa37', 'raiz37', 'pufa37', 'nt37', 'coroa36', 'raiz36', 'pufa36', 'nt36', 'coroa35', 'raiz35', 'pufa35', 'nt35', 'coroa34', 'raiz34', 'pufa34', 'nt34', 'coroa33', 'raiz33', 'pufa33', 'nt33', 'coroa32', 'raiz32', 'pufa32', 'nt32', 'coroa31', 'raiz31', 'pufa31', 'nt31', 'coroa41', 'raiz41', 'pufa41', 'nt41', 'coroa42', 'raiz42', 'pufa42', 'nt42', 'coroa43', 'raiz43', 'pufa43', 'nt43', 'coroa44', 'raiz44', 'pufa44', 'nt44', 'coroa45', 'raiz45', 'pufa45', 'nt45', 'coroa46', 'raiz46', 'pufa46', 'nt46', 'coroa47', 'raiz47', 'pufa47', 'nt47', 'coroa48', 'raiz48', 'pufa48', 'nt48', 'chave_caninos', 'sobremordida', 'sobressaliencia', 'mcposterior', 'urgencia', 'trauma12', 'trauma11', 'trauma21', 'trauma22', 'trauma32', 'trauma31', 'trauma41', 'trauma42', 'ss_sd', 'calc_sd', 'bolsa_sd', 'pip_sd', 'ss_sc', 'calc_sc', 'bolsa_sc', 'pip_sc', 'ss_se', 'calc_se', 'bolsa_se', 'pip_se', 'ss_ie', 'calc_ie', 'bolsa_ie', 'pip_ie', 'ss_ic', 'calc_ic', 'bolsa_ic', 'pip_ic', 'ss_id', 'calc_id', 'bolsa_id', 'pip_id', 'usa_apal_orto', 'dai1', 'dai2', 'dai3', 'dai4', 'dai5', 'dai6', 'dai7', 'dai8', 'dai9', 'dai10', 'dai11', 'usoprotsup', 'necprotsup', 'usoprotinf', 'necprotinf', 'necsup_parcial_total', 'necinf_parcial_total', 'necprot', 'ceod', 'dhigidos', 'drestaurado_sem_carie', 'dcariado_total', 'dcariado', 'drestaurado_com_carie', 'dperdido', 'carie', 'cariado', 'cariado_total', 'perdido', 'restaurado_com_carie', 'restaurado_sem_carie', 'livrecarie', 'lvcarie', 'higidos', 'cpod', 'pufa_total', 'pufa_envolvpulpar', 'pufa_ulceracao', 'pufa_fistula', 'pufa_abscesso', 'pufa_prev_deciduo', 'pufa_prev_permanente', 'pufa_total_permanente_5a', 'pufa_envolvpulpar_permanente_5a', 'pufa_ulceracao_permanente_5a', 'pufa_fistula_permanente_5a', 'pufa_abscesso_permanente_5a', 'razao_pufa_carie', 'raiz_higida', 'raiz_cariada', 'raiz_cariada_total', 'raiz_rest_cariada', 'raiz_rest', 'raiz_implante', 'raiz_exposta', 'raiz_nao_exposta', 'raiz_excluida', 'nt_nenhum', 'nt_rest_1superf', 'nt_rest_2superf', 'nt_coroa', 'nt_faceta', 'nt_tratpulpar', 'nt_extracao', 'nt_remin', 'nt_selante', 'nt_seminfor', 'nenhumtrauma', 'fraturatratada', 'fraturaesmalte', 'fraturaesmalte_dentina', 'envolvpulpar', 'perdatrauma', 'outrosdanos', 'prevtrauma', 'qqtrauma', 'nsextantes_semsangramento', 'nsextantes_sangramento', 'nsextantes_ssexcluidos', 'nsextantes_semcalculo', 'nsextantes_comcalculo', 'nsextantes_calcexcluido', 'nsextantes_bolsahigido', 'nsextantes_bolsarasa', 'nsextantes_bolsaprofunda', 'nsextantes_bolsaexcluidos', 'nsextantes_pip0', 'nsextantes_pip1', 'nsextantes_pip2', 'nsextantes_pip3', 'nsextantes_pip4', 'nsextantes_pip9', 'cpi', 'pip', 'prevss', 'prevcalc', 'prevbolsarasa', 'prevbolsaprofunda', 'dai', 'catdai', 'edentulismo', 'urgencia_agrupado', 'sm', 'smcat', 'rendapercapita', 'estrato', 'wi_pesodel', 'grupo_estudo', 'ano']

Dtypes:
codigo              int64
setor               int64
cod_uf              int64
uf2                 int64
regiao              int64
                   ...
rendapercapita    float64
estrato             int64
wi_pesodel        float64
grupo_estudo       object
ano                 int64
Length: 413, dtype: object

Nulos por coluna (count):
pufa_envolvpulpar_permanente_5a    38866
pufa_fistula_permanente_5a         38866
pufa_abscesso_permanente_5a        38866
pufa_ulceracao_permanente_5a       38866
pufa_total_permanente_5a           38866
anosestudo_mae                     34170
fraturaesmalte_dentina             34040
envolvpulpar                       34040
perdatrauma                        34040
outrosdanos                        34040
prevtrauma                         34040
qqtrauma                           34040
fraturaesmalte                     34040
nenhumtrauma                       34040
fraturatratada                     34040
trauma32                           34022
trauma21                           34022
trauma12                           34022
trauma41                           34022
trauma31                           34022
dtype: int64

In [4]:
# 3) Estatísticas descritivas (numéricas e categóricas separadas)
num = df.select_dtypes(include=[np.number])
cat = df.select_dtypes(exclude=[np.number])

print('Numéricas: count, mean, std, min, 25%, 50%, 75%, max')
display(num.describe().T)

print('\nCategóricas (top 10 unique counts)')
display(cat.nunique().sort_values(ascending=False).head(20))

Numéricas: count, mean, std, min, 25%, 50%, 75%, max

,count,mean,std,min,25%,50%,75%,max
codigo,40720.0,2.036050e+04,1.175500e+04,1.000000e+00,1.018075e+04,2.036050e+04,3.054025e+04,4.072000e+04
setor,40720.0,2.963368e+14,1.257791e+14,1.100023e+14,2.110906e+14,2.704302e+14,4.106902e+14,5.300108e+14
cod_uf,40720.0,2.955226e+01,1.256584e+01,1.100000e+01,2.100000e+01,2.700000e+01,4.100000e+01,5.300000e+01
uf2,40720.0,1.411555e+01,7.890697e+00,1.000000e+00,8.000000e+00,1.400000e+01,2.100000e+01,2.700000e+01
regiao,40720.0,2.584897e+00,1.368395e+00,1.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00,5.000000e+00
...,...,...,...,...,...,...,...,...
smcat,40720.0,4.480476e+00,3.254757e+00,1.000000e+00,2.000000e+00,3.000000e+00,9.000000e+00,9.000000e+00
rendapercapita,27802.0,9.610118e+02,1.306563e+03,0.000000e+00,3.750000e+02,6.060000e+02,1.156750e+03,6.000000e+04
estrato,40720.0,2.631547e+01,1.517111e+01,1.000000e+00,1.200000e+01,2.600000e+01,3.900000e+01,5.300000e+01
wi_pesodel,40720.0,1.615179e+03,5.230682e+03,7.000000e+00,1.053933e+02,3.285083e+02,1.076400e+03,1.483261e+05
ano,40720.0,3.000000e+00,0.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00

Categóricas (top 10 unique counts)

cidade          391
grupo_estudo      5
dtype: int64

In [ ]:
# 4) Contagens e distribuições para colunas-chave (exemplos)
cols_cat = ['regiao','uf2','cidade','escolaridade']
for c in cols_cat:
    if c in df.columns:
        print('----', c, '----')
        display(df[c].value_counts().head(10))

# Distribuição de uma variável numérica exemplar
if 'idade' in df.columns:
    plt.figure(figsize=(8,4))
    df['idade'].dropna().astype(float).hist(bins=30)
    plt.title('Histograma - idade')
    plt.xlabel('idade')
    plt.show()

# Countplot de regiao (se existir)
if 'regiao' in df.columns:
    plt.figure(figsize=(6,3))
    sns.countplot(data=df, x='regiao')
    plt.title('Contagem por regiao')
    plt.show()